### ISSUE TITLE
lags

### ISSUE THREAD

**Issue by frankinshtein** [madmaw/marmalade-openal#1]
Sounds are playing with lags.
The reason is that you are not using GEN callbacks and just calling from thread
s3eSoundChannelPlay(data->channel, (int16*)data->buffer, Device->UpdateSize, 1, 0);
It isn't precision way and it could interrupt currently playing stream or play with delay
Have you tested it? Or used it anywhere? Or maybe didn't commit everything?

**Comment by madmaw** [comment]
I'm afraid what you see there is all I did. By the time I got OpenAL working in Marmalade I didn't need it anymore, so the project is somewhat unfinished. The audio driver I wrote is quite basic, I had a go at writing a better one that used callbacks and also supported 3D sound (I think the code for that is in there too, but disabled), but couldn't get it to work. 

The good news is that the OpenAL source is really well written and the drivers aren't that hard to understand (I'm not a c programmer by trade and I managed, if only if in a basic capacity, to get it going) so it's possible that if you have a day or two, you could get it to work a lot better.

**Comment by Ilya-d** [comment]
Yes, the sound glitches when played. I wasn't able to make it work through callbacks left commented in the code.
frankinshtein, if you will find out how to fix it, pls post here your solution.

**Comment by Ilya-d** [comment]
Yaay! It works!

In s3e_reset_playback i replaced threadstart with commented code:
s3eSoundChannelRegister(data->channel, S3E_CHANNEL_GEN_AUDIO, s3e_more_audio, device);
s3eSoundChannelRegister(data->channel, S3E_CHANNEL_GEN_AUDIO_STEREO, s3e_more_audio, device);
s3eSoundChannelPlay(data->channel, (int16*)data->buffer, data->size, 0, 0);

And in s3e_more_audio callback containing:
aluMixData(pDevice, info->m_Target, info->m_NumSamples);
return info->m_NumSamples;

in s3e_open_playback i replaced mono with stereo and sound became stereo =)
device->FmtChans = DevFmtStereo;

Now I only having troubles with frequencies, when audio is 22KGz and device is 44KGz, sound is played with double speed and vice versa.

**Comment by madmaw** [comment]
Congratulations! I've just added you as a "collaborator", which I hope means you can commit changes to this repository. I don't think anyone would have a problem with you overwriting the existing driver with a working, callback-based, stereo version.

I'm surprised that's all that was needed, I guess I was closer to getting it working than I thought.

**Comment by frankinshtein** [comment]
great news!:) I would try

**Comment by Ilya-d** [comment]
Can't push changes to github, I'm not very experienced with git =(

I also fixed frequencies problem, in s3e_open_playback:

if( s3eSoundGetInt(S3E_SOUND_STEREO_ENABLED)) {
  device->FmtChans = DevFmtStereo;
} else {
  device->FmtChans = DevFmtMono;
}
//device->Frequency = s3eSoundChannelGetInt(data->channel, S3E_CHANNEL_RATE);
// when generating sound, channel frequency is ignored
device->Frequency = s3eSoundGetInt(S3E_SOUND_OUTPUT_FREQ);

**Comment by frankinshtein** [comment]
try pls commit, or send patch
I added your changes but it is crashing

**Comment by Ilya-d** [comment]
Ok I will try to deal with these ssh keys tomorow... 
Btw, you need to call alcInit() from alc.h before using openal.

**Comment by madmaw** [comment]
Ilya-d committed the fixes and it, presumably, worked. On behalf of everyone using this project, a big thank you
