### ISSUE TITLE
Crashing in alSourceUnqueueBuffers

### ISSUE THREAD

**Issue by damucz** [madmaw/marmalade-openal#10]
I wrote a layer on top of your openal port, which is decoding data and uses several channels to play oggs. However playing more sources is very unstable.

When playing two streamed oggs, as soon as the first ends, final buffers should be released and alSourceUnqueueBuffers is called. Then releasing BufferList (alSource.c:1728) is releasing wrong memory.

There is a big chance I'm doing something wrong. Then please tell me how is this openal port supposed to be used. I used this http://devmaster.net/posts/2895/openal-lesson-8-oggvorbis-streaming-using-the-source-queue .

Can I stream more oggs at once?

Playing without streaming or just one stream is fine.
dan@ger.cz , skype damucz

**Comment by vedran-** [comment]
damucz, I think you might be onto something. I usually play just one stream + sound effects, but (very) occasionally I do get strange errors, and they seem to be connected with ogg streaming. My game is to be released for world next week, I will check again the streaming and report back.

**Comment by damucz** [comment]
On my side. Using wrong buffers somehow. :(
